intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{box2d}: $pub/{$pub_hdrs}
lib{box2d}: {hxx cxx}{**} $impl_libs $intf_libs

out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
				-Dbox2d_EXPORTS

{hbmis objs}{*}: cxx.poptions += -DB2_SHARED

lib{box2d}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

libs{box2d}: cxx.export.poptions += -DB2_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{box2d}: bin.lib.version = "-$version.project_id"
else
  lib{box2d}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}: install = false
